# Menu
menu:
  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/crossed-arrows.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ireland/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: Read More...

# Tags
show_count: true

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # true
  clientID: 95b8cb4f85e51b8251dc # GitHub Application Client ID
  clientSecret: 95b54c5509358b005f567e2a646651383a47e70e # Client Secret
  repo: gitalk-repo # Repository name
  owner: amaothree # GitHub ID
  admin: amaothree # GitHub ID
